### ISSUE TITLE
plot to png file

### ISSUE THREAD

**Issue by bugface** [MarkCLewis/SwiftVis2#1]
Hi Dr. Lewis,

I am using the swiftVis2 for plotting but have a problem. I would like to persist a plot as a png file but I cannot find such a method. 
Also, I tried the ImageIO but no success (e.g. ImageIO.write(plot, "png", new File("temp.png"))) because the first arg must be a type of java.awt.image.RenderedImage. Could you show how can I save the plot (e.g. Plot.scatterPlot) as a png file?

**Comment by MarkCLewis** [comment]
The FXRenderer has one menu item for saving the image to a file. If you want to automate this and not have to use the menu option, you can look at the code for that menu option to see what I'm doing. JavaFX doesn't make it all that easy to draw to an Image, but there is a snapshot method that gets the job done.

**Comment by MarkCLewis** [comment]
I just pushed and I added a method called saveToImage in FXRenderer. In minimal testing is does what the name says and saves off a PNG file of the specified size. Due to how JavaFX works, it briefly brings up a Scene to do that in. It appears as a tiny window, then goes away. Depending on the number of elements in the plot, you might not even notice it pop up.
