### ISSUE TITLE
Does this library support animated plots?

### ISSUE THREAD

**Issue by FA5I** [MarkCLewis/SwiftVis2#8]
Hello,

Does this library support animated plots? I.e. say I have a model and it creates a plot frame by frame?

Thank you!

**Comment by MarkCLewis** [comment]
Currently, it doesn't do that very well. There is a concept called an Updater (https://github.com/MarkCLewis/SwiftVis2/blob/master/core/src/main/scala/swiftvis2/plotting/renderer/Updater.scala) that can be used to give this type of functionality. The `apply` method of the SwingRenderer (https://github.com/MarkCLewis/SwiftVis2/blob/master/swingrenderer/src/main/scala/swiftvis2/plotting/renderer/SwingRenderer.scala) returns an updater. When you call `update` on the updater, you pass it the modified plot and it repaints the window with that plot. In theory, if your plots draw quickly, you should be able to use that to produce an animation.

When I want to make actual movies, I generally use the SwingRenderer to save the frame as PNG files then use a program like mencoder (part of mplayer, http://www.mplayerhq.hu/design7/news.html) to stitch the frames into a movie. This approach will make something that is better for viewing, but for some uses, the Updater will work better. My own plots are often very large and take a while to draw, so the interactive approach causes problems because none of the plotting libraries tell you when the image is fully rendered, so you can't wait for that to start the next rendering. I have a feeling though that if your plot doesn't have a million elements in it (which mine frequently do) that the Updater approach will work well.

**Comment by FA5I** [comment]
Ok thank you for the comprehensive reply! Very much appreciated.
